config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#top'
  get 'home/about', to: 'home#about', as: :about
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:show, :index, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :profile_image
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }



  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to @book
    else
      @user = current_user
      @books = Book.all
      render 'books/index'
    end
  end

  def index
    @book = Book.new
    @user = current_user
    @books = Book.all
    
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user_id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash["notice"] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
    render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to users_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new_book.html.erb
<h2 class="mt-3">New Book</h2>
<%= form_with model: book do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <div class="row">
      <div class="col">
        <%= f.text_field :title, class:"form-control" %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <div class="row">
      <div class="col">
        <%= f.text_area :body, class:"form-control" %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class:"btn btn-success" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model: @book do |f| %> 
      
      <% if @book.errors.any? %>
        <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <div class="form-group">
        <label for="inputTitle">Title</label>
        <div class="row">
          <div class="col">
            <%= f.text_field :title, class:"form-control" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <label for="inputOpinion">Opinion</label>
        <div class="row">
          <div class="col">
            <%= f.text_area :body, class:"form-control" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.submit 'Update Book', class: "btn btn-success" %>
      </div>
      <% end %>

      <div><%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", "/books" %></div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
    <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>


<div class="row">
  <div class="col-md-3"> 
    <%= render 'users/info', user: @user %>
    <%= render 'new_book', book: @book %>
  </div>


<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
    <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
      </tr>
    </thead>
    <% @books.each do |book| %>
      <tr>
        <td><%= image_tag book.user.get_profile_image(100,100) %></td>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </table>
</div>
</div>

app/views/books/show.html.erb
<div>
  <p><%= flash[:notice] %></p>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
      <%= render 'new_book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td><%= image_tag @book.user.get_profile_image(100,100) %>
              <br><%= link_to @book.user.name, user_path(@book.user) %></td>
            <td><%= link_to @book.title, book_path(@book) %></td>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
            <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success" %></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, class:"btn btn-sm btn-danger" %></td> 
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<main>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">
        Welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>!
      </h1>
    </div>
  </div>
</main>

app/views/home/top.html.erb
<div>
  <p><%= flash[:notice] %><p>
</div>

<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
    <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>!!</h1>
      <p>In <i class="fa-solid fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions, impressions, and emotions</p>
      <p>about various books!</p>
    <div class="btn-wrapper col-10 mx-auto">
      <div class="row">
        <a class="btn btn-info btn-sm btn-block mb-3" href="/users/sign_in">Log in</a>
        <a class="btn btn-success btn-sm btn-block mb-3" href="/users/sign_up">Sign up</a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

        <script src="https://kit.fontawesome.com/56eb33049c.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
              <i class="fa-solid fa-house"></i> Home
            <% end %>
          </li>
          </li>
          <li class="nav-item">
            <%= link_to users_path, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-users"></i> Users
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to books_path, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-book-open"></i> Books
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-right-from-bracket"></i> Log out
            <% end %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to root_path, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-house"></i> Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to about_path, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-link"></i> About 
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-user-plus"></i> Sign Up
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-right-to-bracket"></i> Log in
            <% end %>
          </li>
          <% end %>
          </ul>
         </div>
        </div>
      </nav>
    </header>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_info.html.erb
<main>
    <div>
      <h2>User Info</h2>
      <%= image_tag user.get_profile_image(100,100) %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>Name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>Introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
      <% if user == current_user %>
      <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
        <i class="fa-solid fa-user-gear"></i>
      <% end %>

    <% end %>
      </div>
  
      
 </main>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

      <%= form_with model: @user do |f| %>
              
      <% if @user.errors.any? %>
        <h3><%=@user.errors.count %> error prohibited this obj from being saved:</h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>


      <div class="form-group">
        <label for="inputName">Name</label>
        <div class="row">
          <div class="col">
            <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class:"form-control" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <label for="inputImage">Image</label>
        <div class="row">
          <div class="col">
            <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
          </div>
        </div>
      </div>
      
      <div class="form-group">
        <label for="inputIntroduction">Introduction</label>
        <div class="row">
          <div class="col">
            <%= f.text_area :introduction, class:"form-control" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.submit "Update User", class: "btn btn-secondary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'info', user: @user %>
      <%= render 'books/new_book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= link_to image_tag(user.get_profile_image(100, 100)), user %></td>
            <td><%= link_to user.name, user %></td>
            <td><%= link_to "Show", user %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div>
  <p><%= flash[:notice] %></p>
</div>

<div class="container px-5 px-sm-0">
  <div class="row"> 
    <div class="col-md-3">
      <%= render 'info', user: @user %>
      <%= render 'books/new_book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
          </thead>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to image_tag(@user.get_profile_image(100, 100)), @user %></td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
          <% end %>
        </table>
    </div>
  </div>
</div> 
  